version: "3.8"

services:

  ui:
    image: fogemulator/fogify-jupyter:v0.02
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8888:8888
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
      - "GRANT_SUDO=yes"
    user: root
  controller:
    image: fogify #name the image and give it a tag [name:tag]
    entrypoint: [ "python", "/code/fogify/main.py", "--controller"]
    # [ "python", "/code/fogify/main.py", "--controller"] -> Production stack | [ "sh", "./controller-entrypoint.sh"] -> Development stack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "5000:5000"
    extra_hosts:
      - ${MANAGER_NAME}:${MANAGER_IP}
      #- "server1-PowerEdge-FC430:192.168.1.1"
  agent:
    image: fogify #name the image and give it a tag [name:tag]
    entrypoint: [ "python", "/code/fogify/main.py", "--agent", "--agent-ip", "${HOST_IP}"]
    # [ "sh", "./agent-entrypoint.sh"] -> Production stack | [ "python", "/code/fogify/main.py", "--agent", "--agent-ip", "${HOST_IP}"] -> Development stack
    extra_hosts:
      - ${MANAGER_NAME}:${MANAGER_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /proc/:/proc/
      - /var/run/docker/:/var/run/docker/
      - /sys/class/net/:/sys/class/net/
      - /usr/bin/nsenter:/usr/bin/nsenter
      - /lib/modules:/lib/modules
      - /sbin/modprobe:/sbin/modprobe
    privileged: true
    cap_add:
      - ALL
    ports:
      - 5500:5500
    environment:
      CONTROLLER_IP: ${MANAGER_IP}
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 9090:8080
    expose:
      - 8080
      - 9090
  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=k6
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=capstone2023
      - DOCKER_INFLUXDB_INIT_ORG=capstone 
      - DOCKER_INFLUXDB_INIT_BUCKET=k6_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sUff4vb6943R91sZ4lm7qsh9g3ljmf4PMm54kQClIp3MOXYyI6BCP34_uUAQDtvTioDQmeXFn6jMNDY4v9gnKQ==
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=capstone2023
